server:
  port: 9002

spring:
  application:
    name: DEPARTMENT-SERVICE
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: admin
    url: jdbc:mariadb://localhost:3306/sample
    username: root
    
    


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost