server:
  port: 9001

spring:
  application:
    name: USER-SERVICE
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: admin
    url: jdbc:mariadb://localhost:3306/sample
    username: root